/logs:
  description: "Logging items belonging to Jobs"
/users:
  description: "Users, can submit Jobs and interact with Daemons"
/jobs:
  description: "Available jobs in the Splay system"
/splayds:
  description: "Splay Daemons, run Jobs"